
version: '3.8'
services:
  rabbitmq:
    image: "rabbitmq:3.13-management"
    ports:
      - "5672:5672"  # AMQP port for clients
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - labtech_net

  redis:
    image: "redis:7.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - labtech_net

  postgres:
    image: "postgres:16.1-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=labtech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - labtech_net

networks:
  labtech_net:
    driver: bridge

volumes:
  rabbitmq_data:
  redis_data:
  postgres_data:
